spring:
  cloud:
    gateway:
      routes:
      - id: test
        uri: "http://httpbin.org:80"
        predicates:
        - Path=/get
      - id: phonebookmanager
        uri: "http://localhost:8083"
        predicates:
        - Path=/phonebookmanager/**
      - id: phoneservice
        uri: "http://localhost:8084"
        predicates:
        - Path=/phoneservice/**
